In [1]:
#建立list
a = [1, 3, 5, 7, 9]
a * 2

b = [2, 4, 6, 8 ,10]
a + b

result = []
for i in range(5):
    result.append(a[i] + b[i])

result

[3, 7, 11, 15, 19]

In [2]:
import numpy as np

#透過list建立ndArray

a_array = np.array([1, 3, 5, 7, 9])
a_array * 2

b_array = np.array([2, 4, 6, 8 ,10])

a_array + b_array

array([ 3,  7, 11, 15, 19])

In [3]:
#使用python建立5個亂數元素的list
import random

#list comprehension
[random.randint(50,100) for _ in range(5)]

[60, 75, 69, 76, 89]

In [4]:
#使用numpy random 建立亂數
import numpy as np
np.random.randint(50,high=100,size=5)

array([75, 98, 93, 95, 59])

In [5]:
np.random.randint(50,high=100,size=(50, 5))

array([[81, 50, 70, 57, 79],
       [75, 59, 89, 56, 97],
       [89, 78, 70, 83, 51],
       [56, 66, 57, 54, 89],
       [57, 73, 55, 53, 53],
       [50, 59, 53, 88, 69],
       [81, 52, 51, 96, 61],
       [80, 94, 55, 74, 91],
       [77, 87, 50, 79, 78],
       [92, 94, 76, 94, 88],
       [52, 91, 58, 83, 83],
       [68, 56, 78, 81, 78],
       [90, 95, 78, 76, 57],
       [71, 90, 93, 84, 99],
       [97, 79, 89, 72, 52],
       [59, 50, 74, 94, 59],
       [95, 72, 73, 54, 52],
       [61, 51, 85, 78, 53],
       [98, 97, 91, 74, 91],
       [94, 62, 57, 59, 68],
       [59, 62, 80, 93, 72],
       [99, 62, 72, 81, 91],
       [87, 84, 54, 71, 76],
       [64, 70, 66, 62, 92],
       [60, 61, 79, 81, 90],
       [58, 67, 90, 64, 71],
       [94, 72, 90, 95, 54],
       [69, 97, 68, 86, 90],
       [73, 64, 98, 72, 66],
       [68, 70, 59, 59, 99],
       [87, 71, 74, 95, 77],
       [81, 59, 73, 77, 65],
       [70, 94, 75, 65, 91],
       [72, 81, 69, 85, 89],
       [58, 78